export const VIETNAM_PROVINCES_34 = [
  'Thành phố Hà Nội',
  'Thành phố Hồ Chí Minh',
  'Thành phố Hải Phòng',
  'Thành phố Đà Nẵng',
  'Thành phố Huế',
  'Thành phố Cần Thơ',
  'Tuyên Quang',
  'Lào Cai',
  'Thái Nguyên',
  'Phú Thọ',
  'Bắc Ninh',
  'Hưng Yên',
  'Ninh Bình',
  'Quảng Trị',
  'Quảng Ngãi',
  'Gia Lai',
  'Khánh Hòa',
  'Lâm Đồng',
  'Đắk Lắk',
  'Đồng Nai',
  'Tây Ninh',
  'Vĩnh Long',
  'Đồng Tháp',
  'Cà Mau',
  'An Giang',
  'Cao Bằng',
  'Lạng Sơn',
  'Lai Châu',
  'Điện Biên',
  'Sơn La',
  'Thanh Hóa',
  'Nghệ An',
  'Hà Tĩnh',
  'Quảng Ninh',
]
